[package]
name = "simple-trading"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
async-graphql = { version = "=7.0.17", default-features = false }
linera-sdk = "0.15.7"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]
