[package]
name = "ai-power-trading"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ai-power-trade-abi = { path = "../abi" }
linera-sdk = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
async-graphql = { workspace = true }