[package]
name = "market-data"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi" }
linera-sdk = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]