[package]
name = "ai-power-trade-abi"
version = "0.1.0"
edition = "2021"

[dependencies]
linera-sdk = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
async-graphql = { workspace = true }